// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations;

[DbContext(typeof(DeliFitContext))]
[Migration("20260722130000_AddIdEnderecoToCarrinho")]
partial class AddIdEnderecoToCarrinho
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.23")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("Core.Atendimento", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<string>("DiaSemana")
                    .IsRequired()
                    .HasColumnType("enum('1','2','3','4','5','6','7')")
                    .HasColumnName("diaSemana")
                    .HasComment("1-Domingo\n2-Segunda\n3-Terça\n4-Quarta\n5-Quinta\n6-Sexta\n7-Sabado");

                b.Property<DateTime?>("HorarioFim")
                    .HasColumnType("datetime")
                    .HasColumnName("horarioFim");

                b.Property<DateTime?>("HorarioInicio")
                    .HasColumnType("datetime")
                    .HasColumnName("horarioInicio");

                b.Property<uint>("IdRestaurante")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idRestaurante");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdRestaurante" }, "fk_Atendimento_Restaurante1_idx");

                b.ToTable("atendimento", (string)null);
            });

        modelBuilder.Entity("Core.Avaliacao", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("descricao");

                b.Property<uint>("IdCliente")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idCliente");

                b.Property<uint>("IdPedido")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idPedido");

                b.Property<decimal>("Nota")
                    .HasPrecision(10)
                    .HasColumnType("decimal(10,2)")
                    .HasColumnName("nota");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdCliente" }, "fk_Avaliacao_Cliente1_idx");

                b.HasIndex(new[] { "IdPedido" }, "fk_Avaliacao_Pedido1_idx");

                b.ToTable("avaliacao", (string)null);
            });

        modelBuilder.Entity("Core.Carrinho", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<string>("FormaDePagamento")
                    .IsRequired()
                    .HasColumnType("enum('P','C','D')")
                    .HasColumnName("formaDePagamento")
                    .HasComment("P para PIX,C para CARTÃO, D para DINHEIRO ");

                b.Property<uint?>("IdCartao")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idCartao");

                b.Property<uint>("IdCliente")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idCliente");

                b.Property<uint?>("IdEndereco")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idEndereco");

                b.Property<string>("MercadoPagoPaymentId")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("mercadoPagoPaymentId");

                b.Property<string>("Observacao")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasColumnName("observacao");

                b.Property<string>("StatusPagamentoCartao")
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)")
                    .HasColumnName("statusPagamentoCartao");

                b.Property<decimal>("ValorFrete")
                    .HasPrecision(10)
                    .HasColumnType("decimal(10,2)")
                    .HasColumnName("valorFrete");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdCartao" }, "fk_Carrinho_Cartao1_idx");

                b.HasIndex(new[] { "IdCliente" }, "fk_Carrinho_Cliente1_idx");

                b.HasIndex(new[] { "IdEndereco" }, "fk_Carrinho_Endereco1_idx");

                b.ToTable("carrinho", (string)null);
            });

        modelBuilder.Entity("Core.Cartao", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<string>("Bandeira")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)")
                    .HasColumnName("bandeira");

                b.Property<string>("Cpf")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("char(11)")
                    .HasColumnName("cpf")
                    .IsFixedLength();

                b.Property<uint>("IdCliente")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idCliente");

                b.Property<string>("MercadoPagoCardId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("mercadoPagoCardId");

                b.Property<string>("MercadoPagoIssuerId")
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)")
                    .HasColumnName("mercadoPagoIssuerId");

                b.Property<string>("MercadoPagoPaymentMethodId")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)")
                    .HasColumnName("mercadoPagoPaymentMethodId");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("nome");

                b.Property<string>("UltimosQuatroDigitos")
                    .IsRequired()
                    .HasMaxLength(4)
                    .HasColumnType("char(4)")
                    .HasColumnName("ultimosQuatroDigitos")
                    .IsFixedLength();

                b.Property<DateTime>("Validade")
                    .HasColumnType("datetime")
                    .HasColumnName("validade");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdCliente" }, "fk_Cartao_Cliente1_idx");

                b.ToTable("cartao", (string)null);
            });

        modelBuilder.Entity("Core.Categoria", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasColumnName("nome");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "Nome" }, "nome_UNIQUE")
                    .IsUnique();

                b.ToTable("categoria", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1u,
                        Nome = "Vegetariano"
                    },
                    new
                    {
                        Id = 2u,
                        Nome = "Vegano"
                    },
                    new
                    {
                        Id = 3u,
                        Nome = "Sem Glúten"
                    },
                    new
                    {
                        Id = 4u,
                        Nome = "Sem Lactose"
                    },
                    new
                    {
                        Id = 5u,
                        Nome = "Fitness"
                    },
                    new
                    {
                        Id = 6u,
                        Nome = "Low Carb"
                    },
                    new
                    {
                        Id = 7u,
                        Nome = "Zero Lactose"
                    },
                    new
                    {
                        Id = 8u,
                        Nome = "Proteico"
                    });
            });

        modelBuilder.Entity("Core.Cliente", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<bool>("Ativo")
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true)
                    .HasColumnName("ativo");

                b.Property<string>("Cpf")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("char(11)")
                    .HasColumnName("cpf")
                    .IsFixedLength();

                b.Property<DateTime>("DataNascimento")
                    .HasColumnType("date")
                    .HasColumnName("dataNascimento");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("email");

                b.Property<string>("MercadoPagoCustomerId")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("mercadoPagoCustomerId");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("nome");

                b.Property<string>("Telefone")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("char(11)")
                    .HasColumnName("telefone")
                    .IsFixedLength();

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.ToTable("cliente", (string)null);
            });

        modelBuilder.Entity("Core.Endereco", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<string>("Bairro")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("bairro");

                b.Property<string>("Cep")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("char(8)")
                    .HasColumnName("cep")
                    .IsFixedLength();

                b.Property<string>("Cidade")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasColumnName("cidade");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("estado");

                b.Property<uint>("IdCliente")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idCliente");

                b.Property<string>("Label")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("varchar(30)")
                    .HasColumnName("label");

                b.Property<string>("Numero")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("numero");

                b.Property<string>("Rua")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("rua");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdCliente" }, "fk_Endereco_Cliente1_idx");

                b.ToTable("endereco", (string)null);
            });

        modelBuilder.Entity("Core.Item", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<float>("Calorias")
                    .HasColumnType("float")
                    .HasColumnName("calorias");

                b.Property<float?>("Carboidratos")
                    .HasColumnType("float")
                    .HasColumnName("carboidratos");

                b.Property<string>("Descricao")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("descricao");

                b.Property<byte[]>("Foto")
                    .HasColumnType("longblob")
                    .HasColumnName("foto");

                b.Property<float?>("Gordura")
                    .HasColumnType("float")
                    .HasColumnName("gordura");

                b.Property<uint>("IdRestaurante")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idRestaurante");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("nome");

                b.Property<decimal>("Preco")
                    .HasPrecision(10)
                    .HasColumnType("decimal(10,2)")
                    .HasColumnName("preco");

                b.Property<float?>("Proteina")
                    .HasColumnType("float")
                    .HasColumnName("proteina");

                b.Property<string>("Restricao")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("restricao");

                b.Property<string>("Tamanho")
                    .HasColumnType("enum('P','M','G')")
                    .HasColumnName("tamanho");

                b.Property<string>("Volume")
                    .HasMaxLength(10)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("volume");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdRestaurante" }, "fk_Item_Restaurante1_idx");

                b.ToTable("item", (string)null);
            });

        modelBuilder.Entity("Core.Pagamento", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<DateTime?>("DataPagamento")
                    .HasColumnType("datetime")
                    .HasColumnName("dataPagamento");

                b.Property<DateTime?>("DataVencimento")
                    .HasColumnType("datetime")
                    .HasColumnName("dataVencimento");

                b.Property<uint>("IdRestaurante")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idRestaurante");

                b.Property<string>("StatusMensalidade")
                    .IsRequired()
                    .HasColumnType("enum('P','E','A')")
                    .HasColumnName("statusMensalidade")
                    .HasComment("P : Pago\nE: Pendente\nA: Atraso");

                b.Property<decimal>("ValorMensalidade")
                    .HasPrecision(10)
                    .HasColumnType("decimal(10,2)")
                    .HasColumnName("valorMensalidade");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdRestaurante" }, "fk_pagamento_Restaurante1_idx");

                b.ToTable("pagamento", (string)null);
            });

        modelBuilder.Entity("Core.Pedido", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<DateTime?>("Data")
                    .HasColumnType("datetime")
                    .HasColumnName("data");

                b.Property<uint>("IdCarrinho")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idCarrinho");

                b.Property<uint>("IdRestaurante")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idRestaurante");

                b.Property<decimal>("Preco")
                    .HasPrecision(10)
                    .HasColumnType("decimal(10,2)")
                    .HasColumnName("preco");

                b.Property<string>("Status")
                    .HasColumnType("enum('P','E','S','F')")
                    .HasColumnName("status")
                    .HasComment("P=Pendente, E=EmPreparo, S=EmEntrega, F=Finalizado");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdCarrinho" }, "fk_Pedido_Carrinho1_idx");

                b.HasIndex(new[] { "IdRestaurante" }, "fk_Pedido_Restaurante1_idx");

                b.ToTable("pedido", (string)null);
            });

        modelBuilder.Entity("Core.Pedidoitem", b =>
            {
                b.Property<uint>("IdPedido")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idPedido");

                b.Property<uint>("IdItem")
                    .HasColumnType("int unsigned")
                    .HasColumnName("idItem");

                b.Property<decimal>("Preco")
                    .HasPrecision(10)
                    .HasColumnType("decimal(10,2)")
                    .HasColumnName("preco");

                b.Property<int>("Quantidade")
                    .HasColumnType("int")
                    .HasColumnName("quantidade");

                b.HasKey("IdPedido", "IdItem")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "IdItem" }, "fk_PedidoItem_Item1_idx");

                b.HasIndex(new[] { "IdPedido" }, "fk_PedidoItem_Pedido1_idx");

                b.ToTable("pedidoitem", (string)null);
            });

        modelBuilder.Entity("Core.Restaurante", b =>
            {
                b.Property<uint>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int unsigned")
                    .HasColumnName("id");

                b.Property<string>("Bairro")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("bairro");

                b.Property<string>("Cep")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("varchar(8)")
                    .HasColumnName("cep");

                b.Property<string>("Cidade")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasColumnName("cidade");

                b.Property<string>("Cnpj")
                    .IsRequired()
                    .HasMaxLength(14)
                    .HasColumnType("char(14)")
                    .HasColumnName("cnpj")
                    .IsFixedLength();

                b.Property<string>("CpfProprietario")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("char(11)")
                    .HasColumnName("cpfProprietario")
                    .IsFixedLength();

                b.Property<string>("Descricao")
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("descricao");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("email");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("estado");

                b.Property<byte[]>("Foto")
                    .HasColumnType("longblob")
                    .HasColumnName("foto");

                b.Property<string>("NomeProprietario")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("nomeProprietario");

                b.Property<string>("NomeRestaurante")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("nomeRestaurante");

                b.Property<string>("Numero")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("numero");

                b.Property<string>("Rua")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("rua");

                b.Property<string>("TelefoneProprietario")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("char(11)")
                    .HasColumnName("telefoneProprietario")
                    .IsFixedLength();

                b.Property<string>("TelefoneRestaurante")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("char(11)")
                    .HasColumnName("telefoneRestaurante")
                    .IsFixedLength();

                b.Property<bool>("Validado")
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("validado");

                b.HasKey("Id")
                    .HasName("PRIMARY");

                b.HasIndex(new[] { "Cnpj" }, "cnpj_UNIQUE")
                    .IsUnique();

                b.HasIndex(new[] { "NomeRestaurante" }, "nomeRestaurante_UNIQUE")
                    .IsUnique();

                b.ToTable("restaurante", (string)null);
            });

        modelBuilder.Entity("categoria_item", b =>
            {
                b.Property<uint>("idCategoria")
                    .HasColumnType("int unsigned");

                b.Property<uint>("idItem")
                    .HasColumnType("int unsigned");

                b.HasKey("idCategoria", "idItem")
                    .HasName("PRIMARY");

                b.HasIndex("idItem");

                b.ToTable("categoria_item", (string)null);
            });

        modelBuilder.Entity("Core.Atendimento", b =>
            {
                b.HasOne("Core.Restaurante", "IdRestauranteNavigation")
                    .WithMany("Atendimentos")
                    .HasForeignKey("IdRestaurante")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_Atendimento_Restaurante1");

                b.Navigation("IdRestauranteNavigation");
            });

        modelBuilder.Entity("Core.Avaliacao", b =>
            {
                b.HasOne("Core.Cliente", "IdClienteNavigation")
                    .WithMany("Avaliacaos")
                    .HasForeignKey("IdCliente")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_Avaliacao_Cliente1");

                b.HasOne("Core.Pedido", "IdPedidoNavigation")
                    .WithMany("Avaliacaos")
                    .HasForeignKey("IdPedido")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_Avaliacao_Pedido1");

                b.Navigation("IdClienteNavigation");

                b.Navigation("IdPedidoNavigation");
            });

        modelBuilder.Entity("Core.Carrinho", b =>
            {
                b.HasOne("Core.Cartao", "IdCartaoNavigation")
                    .WithMany("Carrinhos")
                    .HasForeignKey("IdCartao")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("fk_Carrinho_Cartao1");

                b.HasOne("Core.Cliente", "IdClienteNavigation")
                    .WithMany("Carrinhos")
                    .HasForeignKey("IdCliente")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_Carrinho_Cliente1");

                b.HasOne("Core.Endereco", "IdEnderecoNavigation")
                    .WithMany("Carrinhos")
                    .HasForeignKey("IdEndereco")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("fk_Carrinho_Endereco1");

                b.Navigation("IdCartaoNavigation");

                b.Navigation("IdClienteNavigation");

                b.Navigation("IdEnderecoNavigation");
            });

        modelBuilder.Entity("Core.Cartao", b =>
            {
                b.HasOne("Core.Cliente", "IdClienteNavigation")
                    .WithMany("Cartaos")
                    .HasForeignKey("IdCliente")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_Cartao_Cliente1");

                b.Navigation("IdClienteNavigation");
            });

        modelBuilder.Entity("Core.Endereco", b =>
            {
                b.HasOne("Core.Cliente", "IdClienteNavigation")
                    .WithMany("Enderecos")
                    .HasForeignKey("IdCliente")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_Endereco_Cliente1");

                b.Navigation("IdClienteNavigation");
            });

        modelBuilder.Entity("Core.Item", b =>
            {
                b.HasOne("Core.Restaurante", "IdRestauranteNavigation")
                    .WithMany("Items")
                    .HasForeignKey("IdRestaurante")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_Item_Restaurante1");

                b.Navigation("IdRestauranteNavigation");
            });

        modelBuilder.Entity("Core.Pagamento", b =>
            {
                b.HasOne("Core.Restaurante", "IdRestauranteNavigation")
                    .WithMany("Pagamentos")
                    .HasForeignKey("IdRestaurante")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_pagamento_Restaurante1");

                b.Navigation("IdRestauranteNavigation");
            });

        modelBuilder.Entity("Core.Pedido", b =>
            {
                b.HasOne("Core.Carrinho", "IdCarrinhoNavigation")
                    .WithMany("Pedidos")
                    .HasForeignKey("IdCarrinho")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_Pedido_Carrinho1");

                b.HasOne("Core.Restaurante", "IdRestauranteNavigation")
                    .WithMany("Pedidos")
                    .HasForeignKey("IdRestaurante")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_Pedido_Restaurante1");

                b.Navigation("IdCarrinhoNavigation");

                b.Navigation("IdRestauranteNavigation");
            });

        modelBuilder.Entity("Core.Pedidoitem", b =>
            {
                b.HasOne("Core.Item", "IdItemNavigation")
                    .WithMany("Pedidoitems")
                    .HasForeignKey("IdItem")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_PedidoItem_Item1");

                b.HasOne("Core.Pedido", "IdPedidoNavigation")
                    .WithMany("Pedidoitems")
                    .HasForeignKey("IdPedido")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_PedidoItem_Pedido1");

                b.Navigation("IdItemNavigation");

                b.Navigation("IdPedidoNavigation");
            });

        modelBuilder.Entity("categoria_item", b =>
            {
                b.HasOne("Core.Categoria", null)
                    .WithMany()
                    .HasForeignKey("idCategoria")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_categoria_has_item_categoria");

                b.HasOne("Core.Item", null)
                    .WithMany()
                    .HasForeignKey("idItem")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_categoria_has_item_item");
            });

        modelBuilder.Entity("Core.Carrinho", b =>
            {
                b.Navigation("Pedidos");
            });

        modelBuilder.Entity("Core.Cartao", b =>
            {
                b.Navigation("Carrinhos");
            });

        modelBuilder.Entity("Core.Cliente", b =>
            {
                b.Navigation("Avaliacaos");

                b.Navigation("Carrinhos");

                b.Navigation("Cartaos");

                b.Navigation("Enderecos");
            });

        modelBuilder.Entity("Core.Endereco", b =>
            {
                b.Navigation("Carrinhos");
            });

        modelBuilder.Entity("Core.Item", b =>
            {
                b.Navigation("Pedidoitems");
            });

        modelBuilder.Entity("Core.Pedido", b =>
            {
                b.Navigation("Avaliacaos");

                b.Navigation("Pedidoitems");
            });

        modelBuilder.Entity("Core.Restaurante", b =>
            {
                b.Navigation("Atendimentos");

                b.Navigation("Items");

                b.Navigation("Pagamentos");

                b.Navigation("Pedidos");
            });
#pragma warning restore 612, 618
    }
}
